// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEz6Ao6t6CCpTRHaiSKoxKoQhnaNqMJyU',
    appId: '1:914348006913:web:2f7c998b5b65b4e1ccea00',
    messagingSenderId: '914348006913',
    projectId: 'campus-sync-b4cff',
    authDomain: 'campus-sync-b4cff.firebaseapp.com',
    storageBucket: 'campus-sync-b4cff.firebasestorage.app',
    measurementId: 'G-MLN5EX338D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqHJ4JPSninV7c-DkVaFgzydPTFzP13SY',
    appId: '1:914348006913:android:be228d640738e1aeccea00',
    messagingSenderId: '914348006913',
    projectId: 'campus-sync-b4cff',
    storageBucket: 'campus-sync-b4cff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXryJpiFXt-hlBkspzZoOXcDR284ecs_s',
    appId: '1:914348006913:ios:efee6fb4712f3949ccea00',
    messagingSenderId: '914348006913',
    projectId: 'campus-sync-b4cff',
    storageBucket: 'campus-sync-b4cff.firebasestorage.app',
    iosBundleId: 'com.example.campusSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXryJpiFXt-hlBkspzZoOXcDR284ecs_s',
    appId: '1:914348006913:ios:efee6fb4712f3949ccea00',
    messagingSenderId: '914348006913',
    projectId: 'campus-sync-b4cff',
    storageBucket: 'campus-sync-b4cff.firebasestorage.app',
    iosBundleId: 'com.example.campusSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEz6Ao6t6CCpTRHaiSKoxKoQhnaNqMJyU',
    appId: '1:914348006913:web:53f2b41cfc2e6c65ccea00',
    messagingSenderId: '914348006913',
    projectId: 'campus-sync-b4cff',
    authDomain: 'campus-sync-b4cff.firebaseapp.com',
    storageBucket: 'campus-sync-b4cff.firebasestorage.app',
    measurementId: 'G-RY9QKYGVXG',
  );
}
